{"name": "test_create_unique_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 201\n +  where 403 = <Response [403]>.status_code", "trace": "client = <utils.api_client.ApiClient object at 0x000001B4489B9760>\n\n    def test_create_unique_user(client):\n        data = {\"email\": \"unique@example.com\", \"password\": \"password\", \"name\": \"UniqueUser\"}\n        response = client.create_user(data)\n>       assert response.status_code == 201\nE       assert 403 == 201\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_user_creation.py:11: AssertionError"}, "start": 1730209339774, "stop": 1730209345178, "uuid": "8022a64d-4093-481f-8843-4a87d88d5f26", "historyId": "631e8f537da41b10e741db83823bcc6b", "testCaseId": "631e8f537da41b10e741db83823bcc6b", "fullName": "tests.test_user_creation#test_create_unique_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creation"}, {"name": "host", "value": "WorkPC"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creation"}]}