{"name": "test_login_invalid_credentials", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('client', <FixtureRequest for <Function test_login_invalid_credentials>>)", "trace": "file C:\\Python\\qa_python_projects\\Diplom\\Diplom_2\\tests\\test_user_login.py, line 7\n  def test_login_invalid_credentials(client):\nE       fixture 'client' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Python\\qa_python_projects\\Diplom\\Diplom_2\\tests\\test_user_login.py:7"}, "start": 1729961600892, "stop": 1729961600892, "uuid": "eeb3bcb7-21ab-4ebd-91f3-7bfbee6053f0", "historyId": "7e62b60a41a59ea3a0f8fee66f7acdd7", "testCaseId": "7e62b60a41a59ea3a0f8fee66f7acdd7", "fullName": "tests.test_user_login#test_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "host", "value": "WorkPC"}, {"name": "thread", "value": "16360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}